spring:
  application:
    name: springboot-demo
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
    master:
      jdbc-url: jdbc:mysql://ubuntu01:3306/demo
      username: root
      password: 1234
    slave1:
      jdbc-url: jdbc:mysql://ubuntu01:3306/demo
      username: read_only
      password: 1234
    slave2:
      jdbc-url: jdbc:mysql://ubuntu01:3306/demo
      username: read_only
      password: 1234

mybatis:
  configuration:
    map-underscore-to-camel-case: true # 驼峰映射